# Site settings
title: Creative Commons Labs
email: webmaster@creativecommons.org
description: > # this means to ignore newlines until "baseurl:"
   Website of the Creative Commons tech team.
baseurl: "/labs/" # the subpath of your site, e.g. /blog/
twitter_username: creativecommons
github_username:  creativecommons

# Build settings
markdown: kramdown
